include dark.conf

# font
# font_family VictorMono NF Medium
font_family JetBrainsMono Nerd Font
# font_family ComicShannsMono Nerd Font
font_size 12

# bell
enable_audio_bell no

# cursor
cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 2

# window
remember_window_size  yes
resize_in_steps yes

# cursor trail
cursor_trail 0
cursor_trail_decay 0.05 0.4
cursor_trail_start_threshold 0
shell_integration no-cursor

# tabs
tab_bar_style powerline 
tab_powerline_style round 
tab_bar_align left

# background opacity
background_opacity 0.95

# mappings
map ctrl+shift+t launch --type=tab --cwd=current --tab-title "kitty"
