{
  imports = [
    ./home-manager/hyprland.nix
    ./home-manager/git.nix
    ./home-manager/zen-browser.nix
    ./home-manager/kitty.nix
    ./home-manager/nixcord.nix
    ./home-manager/swww.nix
    ./home-manager/waybar.nix
    ./home-manager/stylix.nix
    ./home-manager/helix.nix
    ./home-manager/fish.nix
    ./home-manager/obsidian.nix
    ./home-manager/zed.nix
    ./home-manager/zellij.nix
    ./home-manager/wofi.nix
    ./home-manager/fastfetch.nix
    ./home-manager/dunst.nix
    ./home-manager/direnv.nix
  ];
}
