$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

source = ./defaults.conf

monitor = DP-3, 1920x1080@165, -1920x600, 1
monitor = HDMI-A-1, 2560x1440@100, 0x0, 1
monitor = eDP-1, 1920x1080, 0x0, 1

exec-once = awww-daemon
exec-once = waybar

bind = , Print, exec, grimblast --freeze copy area
bind = $mainMod, W, exec, change-wallpaper
bind = $mainMod, F, fullscreen

input {
    kb_layout = br
    kb_options = grp:win_space_toggle
    kb_variant =
    kb_model =
    kb_rules =

    follow_mouse = 2
    accel_profile = flat
    natural_scroll = false

    sensitivity = 0
}

general {
    gaps_in = 2
    gaps_out = 4
    border_size = 1

    col.active_border = rgba(f38ba8ff) rgba(fab387ff)
    col.inactive_border = rgba(45475aff)
}

decoration {
    rounding = 0
    active_opacity = 1
    inactive_opacity = 0.98

    shadow {
        enabled = false
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        vibrancy = 0.2696
    }
}

animations {
    enabled = yes, please :3

    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1

    animation = workspaces, 1, 1.5, easeInOutCubic
    animation = workspacesIn, 1, 1.5, easeInOutCubic
    animation = workspacesOut, 1, 1.5, easeInOutCubic
}
