bind = , Print, exec, grimblast --freeze copy area
bind = SHIFT, Print, exec, grimblast --freeze save area - | satty --filename - --output-filename "$HOME/Pictures/screenshots/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png" --early-exit --actions-on-enter save-to-clipboard --save-after-copy --copy-command 'wl-copy' --disable-notifications
bind = $mainMod, F, fullscreen
bind = $mainMod, T, exec, killall -SIGUSR1 waybar
