# still sourcing default while adding my own configs
source = ./default.conf

source = ./init.conf
source = ./input.conf
source = ./bindings.conf
source = ./rules.conf
source = ./animations.conf
source = ./monitor.conf

general {
    border_size = 0
    no_border_on_floating = true
    gaps_in = 5
    gaps_out = 10
}


decoration {
    rounding = 6
    dim_special = 0.4
    shadow {
        enabled = false
    }
}

decoration:blur {
    passes = 2
    size = 4
    noise = 0.0125
    popups = true
}

