# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us, br
    kb_options = grp:win_space_toggle
    kb_variant =
    kb_model =
    kb_rules =

    follow_mouse = 2
    #accel_profile = flat

    sensitivity = 0
}

misc {
    middle_click_paste = false
}
